# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'casedialog.ui'
#
# Created: Mon Sep 28 11:17:30 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CaseDialog(object):
    def setupUi(self, CaseDialog):
        CaseDialog.setObjectName(_fromUtf8("CaseDialog"))
        CaseDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        CaseDialog.resize(560, 566)
        self.gridLayout = QtGui.QGridLayout(CaseDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mapcartoucheView = QtGui.QGraphicsView(CaseDialog)
        self.mapcartoucheView.setObjectName(_fromUtf8("mapcartoucheView"))
        self.gridLayout.addWidget(self.mapcartoucheView, 18, 0, 1, 1)
        self.exerciseGroupBox = QtGui.QGroupBox(CaseDialog)
        self.exerciseGroupBox.setCheckable(True)
        self.exerciseGroupBox.setChecked(False)
        self.exerciseGroupBox.setObjectName(_fromUtf8("exerciseGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.exerciseGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.exerciseGroupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.coursetitleLE = QtGui.QLineEdit(self.frame)
        self.coursetitleLE.setObjectName(_fromUtf8("coursetitleLE"))
        self.gridLayout_3.addWidget(self.coursetitleLE, 3, 1, 1, 1)
        self.exercisetitleLE = QtGui.QLineEdit(self.frame)
        self.exercisetitleLE.setObjectName(_fromUtf8("exercisetitleLE"))
        self.gridLayout_3.addWidget(self.exercisetitleLE, 2, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.exerciseorganisationLE = QtGui.QLineEdit(self.frame)
        self.exerciseorganisationLE.setObjectName(_fromUtf8("exerciseorganisationLE"))
        self.gridLayout_3.addWidget(self.exerciseorganisationLE, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.documenttitleLE = QtGui.QLineEdit(self.frame)
        self.documenttitleLE.setObjectName(_fromUtf8("documenttitleLE"))
        self.gridLayout_3.addWidget(self.documenttitleLE, 3, 3, 1, 1)
        self.exercisedateLE = QtGui.QLineEdit(self.frame)
        self.exercisedateLE.setObjectName(_fromUtf8("exercisedateLE"))
        self.gridLayout_3.addWidget(self.exercisedateLE, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.exerciseGroupBox, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(CaseDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 19, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(CaseDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.classificationLE = QtGui.QLineEdit(CaseDialog)
        self.classificationLE.setObjectName(_fromUtf8("classificationLE"))
        self.horizontalLayout.addWidget(self.classificationLE)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(CaseDialog)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.placedateLE = QtGui.QLineEdit(self.frame_2)
        self.placedateLE.setObjectName(_fromUtf8("placedateLE"))
        self.gridLayout_4.addWidget(self.placedateLE, 0, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.troopstitleLE = QtGui.QLineEdit(self.frame_2)
        self.troopstitleLE.setObjectName(_fromUtf8("troopstitleLE"))
        self.gridLayout_4.addWidget(self.troopstitleLE, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 4, 0, 1, 1)
        self.codenameLE = QtGui.QLineEdit(self.frame_2)
        self.codenameLE.setObjectName(_fromUtf8("codenameLE"))
        self.gridLayout_4.addWidget(self.codenameLE, 1, 1, 1, 1)
        self.cartouchecircumscriptionLE = QtGui.QLineEdit(self.frame_2)
        self.cartouchecircumscriptionLE.setObjectName(_fromUtf8("cartouchecircumscriptionLE"))
        self.gridLayout_4.addWidget(self.cartouchecircumscriptionLE, 2, 1, 1, 1)
        self.supplementtitleLE = QtGui.QLineEdit(self.frame_2)
        self.supplementtitleLE.setObjectName(_fromUtf8("supplementtitleLE"))
        self.gridLayout_4.addWidget(self.supplementtitleLE, 3, 1, 1, 1)
        self.scaletitleLE = QtGui.QLineEdit(self.frame_2)
        self.scaletitleLE.setObjectName(_fromUtf8("scaletitleLE"))
        self.gridLayout_4.addWidget(self.scaletitleLE, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)

        self.retranslateUi(CaseDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CaseDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CaseDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CaseDialog)

    def retranslateUi(self, CaseDialog):
        CaseDialog.setWindowTitle(_translate("CaseDialog", "MapCartouche", None))
        self.exerciseGroupBox.setTitle(_translate("CaseDialog", "Exercise", None))
        self.label_2.setText(_translate("CaseDialog", "Exercise Date:", None))
        self.label_12.setText(_translate("CaseDialog", "Document Title:", None))
        self.label_5.setText(_translate("CaseDialog", "Course Title:", None))
        self.label_11.setText(_translate("CaseDialog", "Exercise Title:", None))
        self.label_4.setText(_translate("CaseDialog", "Exercise Organisation:", None))
        self.label_3.setText(_translate("CaseDialog", "Classification:", None))
        self.label_6.setText(_translate("CaseDialog", "Troops Title:", None))
        self.label_13.setText(_translate("CaseDialog", "Place, Date:", None))
        self.label_7.setText(_translate("CaseDialog", "Codename:", None))
        self.label_8.setText(_translate("CaseDialog", "Cartouche Circumscription:", None))
        self.label_9.setText(_translate("CaseDialog", "Supplement Title:", None))
        self.label_10.setText(_translate("CaseDialog", "Scale Title:", None))

