# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cartouchedialog.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CartoucheDialog(object):
    def setupUi(self, CartoucheDialog):
        CartoucheDialog.setObjectName(_fromUtf8("CartoucheDialog"))
        CartoucheDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        CartoucheDialog.resize(521, 566)
        self.gridLayout = QtGui.QGridLayout(CartoucheDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mapcartoucheView = QtGui.QGraphicsView(CartoucheDialog)
        self.mapcartoucheView.setEnabled(False)
        self.mapcartoucheView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mapcartoucheView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mapcartoucheView.setObjectName(_fromUtf8("mapcartoucheView"))
        self.gridLayout.addWidget(self.mapcartoucheView, 17, 0, 1, 1)
        self.exerciseGroupBox = QtGui.QGroupBox(CartoucheDialog)
        self.exerciseGroupBox.setCheckable(True)
        self.exerciseGroupBox.setChecked(False)
        self.exerciseGroupBox.setObjectName(_fromUtf8("exerciseGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.exerciseGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.exerciseGroupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.exercisedateLE = QtGui.QDateEdit(self.frame)
        self.exercisedateLE.setCalendarPopup(True)
        self.exercisedateLE.setObjectName(_fromUtf8("exercisedateLE"))
        self.gridLayout_3.addWidget(self.exercisedateLE, 1, 0, 1, 1)
        self.coursetitleLE = QtGui.QLineEdit(self.frame)
        self.coursetitleLE.setObjectName(_fromUtf8("coursetitleLE"))
        self.gridLayout_3.addWidget(self.coursetitleLE, 3, 0, 1, 1)
        self.exercisetitleLE = QtGui.QLineEdit(self.frame)
        self.exercisetitleLE.setObjectName(_fromUtf8("exercisetitleLE"))
        self.gridLayout_3.addWidget(self.exercisetitleLE, 2, 2, 1, 1)
        self.documenttitleLE = QtGui.QLineEdit(self.frame)
        self.documenttitleLE.setObjectName(_fromUtf8("documenttitleLE"))
        self.gridLayout_3.addWidget(self.documenttitleLE, 3, 2, 1, 1)
        self.classification1 = QtGui.QComboBox(self.frame)
        self.classification1.setEditable(True)
        self.classification1.setObjectName(_fromUtf8("classification1"))
        self.gridLayout_3.addWidget(self.classification1, 1, 2, 1, 1)
        self.exerciseorganisationLE = QtGui.QLineEdit(self.frame)
        self.exerciseorganisationLE.setObjectName(_fromUtf8("exerciseorganisationLE"))
        self.gridLayout_3.addWidget(self.exerciseorganisationLE, 2, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.exerciseGroupBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(CartoucheDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 18, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(CartoucheDialog)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.supplementtitleLE = QtGui.QLineEdit(self.frame_2)
        self.supplementtitleLE.setObjectName(_fromUtf8("supplementtitleLE"))
        self.gridLayout_4.addWidget(self.supplementtitleLE, 5, 0, 1, 2)
        self.cartouchecircumscriptionLE = QtGui.QLineEdit(self.frame_2)
        self.cartouchecircumscriptionLE.setObjectName(_fromUtf8("cartouchecircumscriptionLE"))
        self.gridLayout_4.addWidget(self.cartouchecircumscriptionLE, 4, 0, 1, 2)
        self.classification2 = QtGui.QComboBox(self.frame_2)
        self.classification2.setEditable(True)
        self.classification2.setObjectName(_fromUtf8("classification2"))
        self.gridLayout_4.addWidget(self.classification2, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.placedateLE = QtGui.QLineEdit(self.frame_2)
        self.placedateLE.setObjectName(_fromUtf8("placedateLE"))
        self.gridLayout_4.addWidget(self.placedateLE, 1, 1, 1, 1)
        self.codenameLE = QtGui.QLineEdit(self.frame_2)
        self.codenameLE.setObjectName(_fromUtf8("codenameLE"))
        self.gridLayout_4.addWidget(self.codenameLE, 2, 0, 1, 2)
        self.troopstitleLE = QtGui.QLineEdit(self.frame_2)
        self.troopstitleLE.setObjectName(_fromUtf8("troopstitleLE"))
        self.gridLayout_4.addWidget(self.troopstitleLE, 1, 0, 1, 1)
        self.scaletitleLE = QtGui.QLineEdit(self.frame_2)
        self.scaletitleLE.setInputMask(_fromUtf8(""))
        self.scaletitleLE.setObjectName(_fromUtf8("scaletitleLE"))
        self.gridLayout_4.addWidget(self.scaletitleLE, 6, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)

        self.retranslateUi(CartoucheDialog)
        self.classification1.setCurrentIndex(-1)
        self.classification2.setCurrentIndex(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CartoucheDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CartoucheDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CartoucheDialog)
        CartoucheDialog.setTabOrder(self.exerciseGroupBox, self.exercisedateLE)
        CartoucheDialog.setTabOrder(self.exercisedateLE, self.classification1)
        CartoucheDialog.setTabOrder(self.classification1, self.exerciseorganisationLE)
        CartoucheDialog.setTabOrder(self.exerciseorganisationLE, self.exercisetitleLE)
        CartoucheDialog.setTabOrder(self.exercisetitleLE, self.coursetitleLE)
        CartoucheDialog.setTabOrder(self.coursetitleLE, self.documenttitleLE)
        CartoucheDialog.setTabOrder(self.documenttitleLE, self.classification2)
        CartoucheDialog.setTabOrder(self.classification2, self.troopstitleLE)
        CartoucheDialog.setTabOrder(self.troopstitleLE, self.placedateLE)
        CartoucheDialog.setTabOrder(self.placedateLE, self.codenameLE)
        CartoucheDialog.setTabOrder(self.codenameLE, self.cartouchecircumscriptionLE)
        CartoucheDialog.setTabOrder(self.cartouchecircumscriptionLE, self.supplementtitleLE)
        CartoucheDialog.setTabOrder(self.supplementtitleLE, self.scaletitleLE)
        CartoucheDialog.setTabOrder(self.scaletitleLE, self.mapcartoucheView)
        CartoucheDialog.setTabOrder(self.mapcartoucheView, self.buttonBox)

    def retranslateUi(self, CartoucheDialog):
        CartoucheDialog.setWindowTitle(_translate("CartoucheDialog", "Map Cartouche", None))
        self.exerciseGroupBox.setTitle(_translate("CartoucheDialog", "Exercise", None))
        self.coursetitleLE.setPlaceholderText(_translate("CartoucheDialog", "Course name", None))
        self.exercisetitleLE.setPlaceholderText(_translate("CartoucheDialog", "Exercise name", None))
        self.documenttitleLE.setPlaceholderText(_translate("CartoucheDialog", "Document name", None))
        self.exerciseorganisationLE.setPlaceholderText(_translate("CartoucheDialog", "Exercise organisation", None))
        self.supplementtitleLE.setPlaceholderText(_translate("CartoucheDialog", "Annex name", None))
        self.cartouchecircumscriptionLE.setPlaceholderText(_translate("CartoucheDialog", "Title of cartouche", None))
        self.placedateLE.setPlaceholderText(_translate("CartoucheDialog", "Place, date", None))
        self.codenameLE.setPlaceholderText(_translate("CartoucheDialog", "\"CODE NAME\"", None))
        self.troopstitleLE.setPlaceholderText(_translate("CartoucheDialog", "Unit", None))
        self.scaletitleLE.setPlaceholderText(_translate("CartoucheDialog", "Scale information", None))

