# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'casedialog.ui'
#
# Created: Thu Oct  8 13:39:03 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CaseDialog(object):
    def setupUi(self, CaseDialog):
        CaseDialog.setObjectName(_fromUtf8("CaseDialog"))
        CaseDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        CaseDialog.resize(560, 566)
        self.gridLayout = QtGui.QGridLayout(CaseDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mapcartoucheView = QtGui.QGraphicsView(CaseDialog)
        self.mapcartoucheView.setObjectName(_fromUtf8("mapcartoucheView"))
        self.gridLayout.addWidget(self.mapcartoucheView, 17, 0, 1, 1)
        self.exerciseGroupBox = QtGui.QGroupBox(CaseDialog)
        self.exerciseGroupBox.setCheckable(True)
        self.exerciseGroupBox.setChecked(False)
        self.exerciseGroupBox.setObjectName(_fromUtf8("exerciseGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.exerciseGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.exerciseGroupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.exercisedateLE = QtGui.QDateEdit(self.frame)
        self.exercisedateLE.setCalendarPopup(True)
        self.exercisedateLE.setObjectName(_fromUtf8("exercisedateLE"))
        self.gridLayout_3.addWidget(self.exercisedateLE, 1, 0, 1, 1)
        self.coursetitleLE = QtGui.QLineEdit(self.frame)
        self.coursetitleLE.setObjectName(_fromUtf8("coursetitleLE"))
        self.gridLayout_3.addWidget(self.coursetitleLE, 3, 0, 1, 1)
        self.exercisetitleLE = QtGui.QLineEdit(self.frame)
        self.exercisetitleLE.setObjectName(_fromUtf8("exercisetitleLE"))
        self.gridLayout_3.addWidget(self.exercisetitleLE, 2, 2, 1, 1)
        self.exerciseorganisationLE = QtGui.QLineEdit(self.frame)
        self.exerciseorganisationLE.setObjectName(_fromUtf8("exerciseorganisationLE"))
        self.gridLayout_3.addWidget(self.exerciseorganisationLE, 2, 0, 1, 1)
        self.documenttitleLE = QtGui.QLineEdit(self.frame)
        self.documenttitleLE.setObjectName(_fromUtf8("documenttitleLE"))
        self.gridLayout_3.addWidget(self.documenttitleLE, 3, 2, 1, 1)
        self.classification1 = QtGui.QComboBox(self.frame)
        self.classification1.setEditable(True)
        self.classification1.setObjectName(_fromUtf8("classification1"))
        self.classification1.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.classification1, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.exerciseGroupBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(CaseDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 18, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(CaseDialog)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.classification2 = QtGui.QComboBox(self.frame_2)
        self.classification2.setEditable(True)
        self.classification2.setObjectName(_fromUtf8("classification2"))
        self.classification2.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.classification2, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 1, 1, 1)
        self.troopstitleLE = QtGui.QLineEdit(self.frame_2)
        self.troopstitleLE.setObjectName(_fromUtf8("troopstitleLE"))
        self.gridLayout_4.addWidget(self.troopstitleLE, 0, 0, 1, 1)
        self.codenameLE = QtGui.QLineEdit(self.frame_2)
        self.codenameLE.setObjectName(_fromUtf8("codenameLE"))
        self.gridLayout_4.addWidget(self.codenameLE, 2, 0, 1, 1)
        self.cartouchecircumscriptionLE = QtGui.QLineEdit(self.frame_2)
        self.cartouchecircumscriptionLE.setObjectName(_fromUtf8("cartouchecircumscriptionLE"))
        self.gridLayout_4.addWidget(self.cartouchecircumscriptionLE, 4, 0, 1, 1)
        self.supplementtitleLE = QtGui.QLineEdit(self.frame_2)
        self.supplementtitleLE.setObjectName(_fromUtf8("supplementtitleLE"))
        self.gridLayout_4.addWidget(self.supplementtitleLE, 5, 0, 1, 1)
        self.scaletitleLE = QtGui.QLineEdit(self.frame_2)
        self.scaletitleLE.setInputMask(_fromUtf8(""))
        self.scaletitleLE.setObjectName(_fromUtf8("scaletitleLE"))
        self.gridLayout_4.addWidget(self.scaletitleLE, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bz1LE = QtGui.QLineEdit(self.frame_2)
        self.bz1LE.setObjectName(_fromUtf8("bz1LE"))
        self.horizontalLayout_3.addWidget(self.bz1LE)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.bz2LE = QtGui.QLineEdit(self.frame_2)
        self.bz2LE.setObjectName(_fromUtf8("bz2LE"))
        self.horizontalLayout_4.addWidget(self.bz2LE)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_4.setStretch(0, 2)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.bz3LE = QtGui.QLineEdit(self.frame_2)
        self.bz3LE.setObjectName(_fromUtf8("bz3LE"))
        self.horizontalLayout_5.addWidget(self.bz3LE)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_5.setStretch(0, 2)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 7, 1, 1, 1)
        self.placedateLE = QtGui.QLineEdit(self.frame_2)
        self.placedateLE.setObjectName(_fromUtf8("placedateLE"))
        self.gridLayout_4.addWidget(self.placedateLE, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)

        self.retranslateUi(CaseDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CaseDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CaseDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CaseDialog)

    def retranslateUi(self, CaseDialog):
        CaseDialog.setWindowTitle(_translate("CaseDialog", "MapCartouche", None))
        self.exerciseGroupBox.setTitle(_translate("CaseDialog", "Exercise", None))
        self.coursetitleLE.setPlaceholderText(_translate("CaseDialog", "Course name", None))
        self.exercisetitleLE.setPlaceholderText(_translate("CaseDialog", "Exercise name", None))
        self.exerciseorganisationLE.setPlaceholderText(_translate("CaseDialog", "Exercise organisation", None))
        self.documenttitleLE.setPlaceholderText(_translate("CaseDialog", "Document name", None))
        self.classification1.setItemText(0, _translate("CaseDialog", "CLASSIFICATION", None))
        self.classification2.setItemText(0, _translate("CaseDialog", "CLASSIFICATION", None))
        self.troopstitleLE.setPlaceholderText(_translate("CaseDialog", "Unit", None))
        self.codenameLE.setPlaceholderText(_translate("CaseDialog", "\"CODE NAME\"", None))
        self.cartouchecircumscriptionLE.setPlaceholderText(_translate("CaseDialog", "Title of cartouche", None))
        self.supplementtitleLE.setPlaceholderText(_translate("CaseDialog", "Annex name", None))
        self.scaletitleLE.setPlaceholderText(_translate("CaseDialog", "Scale information", None))
        self.bz1LE.setPlaceholderText(_translate("CaseDialog", "Blank line", None))
        self.bz2LE.setPlaceholderText(_translate("CaseDialog", "Blank line", None))
        self.bz3LE.setPlaceholderText(_translate("CaseDialog", "Blank line", None))
        self.placedateLE.setPlaceholderText(_translate("CaseDialog", "Place, date", None))

