# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printdialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PrintDialog(object):
    def setupUi(self, PrintDialog):
        PrintDialog.setObjectName(_fromUtf8("PrintDialog"))
        PrintDialog.resize(494, 670)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("printer"))
        PrintDialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(PrintDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_border = QtGui.QLabel(PrintDialog)
        self.label_border.setObjectName(_fromUtf8("label_border"))
        self.gridLayout.addWidget(self.label_border, 5, 0, 1, 1)
        self.label_extent = QtGui.QLabel(PrintDialog)
        self.label_extent.setObjectName(_fromUtf8("label_extent"))
        self.gridLayout.addWidget(self.label_extent, 4, 0, 1, 1)
        self.spinBox_border = QtGui.QDoubleSpinBox(PrintDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_border.sizePolicy().hasHeightForWidth())
        self.spinBox_border.setSizePolicy(sizePolicy)
        self.spinBox_border.setKeyboardTracking(False)
        self.spinBox_border.setDecimals(0)
        self.spinBox_border.setMinimum(15.0)
        self.spinBox_border.setMaximum(1000.0)
        self.spinBox_border.setObjectName(_fromUtf8("spinBox_border"))
        self.gridLayout.addWidget(self.spinBox_border, 5, 1, 1, 1)
        self.widget_extent = QtGui.QWidget(PrintDialog)
        self.widget_extent.setObjectName(_fromUtf8("widget_extent"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_extent)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineedit_ymin = QtGui.QLineEdit(self.widget_extent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_ymin.sizePolicy().hasHeightForWidth())
        self.lineedit_ymin.setSizePolicy(sizePolicy)
        self.lineedit_ymin.setObjectName(_fromUtf8("lineedit_ymin"))
        self.gridLayout_2.addWidget(self.lineedit_ymin, 1, 2, 1, 1)
        self.label_xmax = QtGui.QLabel(self.widget_extent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xmax.sizePolicy().hasHeightForWidth())
        self.label_xmax.setSizePolicy(sizePolicy)
        self.label_xmax.setObjectName(_fromUtf8("label_xmax"))
        self.gridLayout_2.addWidget(self.label_xmax, 0, 3, 1, 1)
        self.label_xmin = QtGui.QLabel(self.widget_extent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xmin.sizePolicy().hasHeightForWidth())
        self.label_xmin.setSizePolicy(sizePolicy)
        self.label_xmin.setObjectName(_fromUtf8("label_xmin"))
        self.gridLayout_2.addWidget(self.label_xmin, 0, 0, 1, 1)
        self.lineedit_xmin = QtGui.QLineEdit(self.widget_extent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_xmin.sizePolicy().hasHeightForWidth())
        self.lineedit_xmin.setSizePolicy(sizePolicy)
        self.lineedit_xmin.setObjectName(_fromUtf8("lineedit_xmin"))
        self.gridLayout_2.addWidget(self.lineedit_xmin, 0, 2, 1, 1)
        self.label_ymax = QtGui.QLabel(self.widget_extent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ymax.sizePolicy().hasHeightForWidth())
        self.label_ymax.setSizePolicy(sizePolicy)
        self.label_ymax.setObjectName(_fromUtf8("label_ymax"))
        self.gridLayout_2.addWidget(self.label_ymax, 1, 3, 1, 1)
        self.label_ymin = QtGui.QLabel(self.widget_extent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ymin.sizePolicy().hasHeightForWidth())
        self.label_ymin.setSizePolicy(sizePolicy)
        self.label_ymin.setObjectName(_fromUtf8("label_ymin"))
        self.gridLayout_2.addWidget(self.label_ymin, 1, 0, 1, 1)
        self.lineedit_ymax = QtGui.QLineEdit(self.widget_extent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_ymax.sizePolicy().hasHeightForWidth())
        self.lineedit_ymax.setSizePolicy(sizePolicy)
        self.lineedit_ymax.setObjectName(_fromUtf8("lineedit_ymax"))
        self.gridLayout_2.addWidget(self.lineedit_ymax, 1, 4, 1, 1)
        self.lineedit_xmax = QtGui.QLineEdit(self.widget_extent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_xmax.sizePolicy().hasHeightForWidth())
        self.lineedit_xmax.setSizePolicy(sizePolicy)
        self.lineedit_xmax.setObjectName(_fromUtf8("lineedit_xmax"))
        self.gridLayout_2.addWidget(self.lineedit_xmax, 0, 4, 1, 1)
        self.label_paperSize = QtGui.QLabel(self.widget_extent)
        self.label_paperSize.setText(_fromUtf8(""))
        self.label_paperSize.setObjectName(_fromUtf8("label_paperSize"))
        self.gridLayout_2.addWidget(self.label_paperSize, 2, 0, 1, 5)
        self.gridLayout.addWidget(self.widget_extent, 4, 1, 1, 1)
        self.groupBox_grid = QgsCollapsibleGroupBox(PrintDialog)
        self.groupBox_grid.setObjectName(_fromUtf8("groupBox_grid"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_grid)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.comboBox_crs = QtGui.QComboBox(self.groupBox_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_crs.sizePolicy().hasHeightForWidth())
        self.comboBox_crs.setSizePolicy(sizePolicy)
        self.comboBox_crs.setObjectName(_fromUtf8("comboBox_crs"))
        self.gridLayout_3.addWidget(self.comboBox_crs, 0, 2, 1, 1)
        self.label_crs = QtGui.QLabel(self.groupBox_grid)
        self.label_crs.setObjectName(_fromUtf8("label_crs"))
        self.gridLayout_3.addWidget(self.label_crs, 0, 0, 1, 1)
        self.spinBox_intervaly = QtGui.QDoubleSpinBox(self.groupBox_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_intervaly.sizePolicy().hasHeightForWidth())
        self.spinBox_intervaly.setSizePolicy(sizePolicy)
        self.spinBox_intervaly.setKeyboardTracking(False)
        self.spinBox_intervaly.setDecimals(10)
        self.spinBox_intervaly.setMaximum(9999999.99)
        self.spinBox_intervaly.setObjectName(_fromUtf8("spinBox_intervaly"))
        self.gridLayout_3.addWidget(self.spinBox_intervaly, 2, 2, 1, 1)
        self.label_intervalx = QtGui.QLabel(self.groupBox_grid)
        self.label_intervalx.setObjectName(_fromUtf8("label_intervalx"))
        self.gridLayout_3.addWidget(self.label_intervalx, 1, 0, 1, 1)
        self.checkBox_gridAnnotations = QtGui.QCheckBox(self.groupBox_grid)
        self.checkBox_gridAnnotations.setObjectName(_fromUtf8("checkBox_gridAnnotations"))
        self.gridLayout_3.addWidget(self.checkBox_gridAnnotations, 3, 0, 1, 3)
        self.spinBox_intervalx = QtGui.QDoubleSpinBox(self.groupBox_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_intervalx.sizePolicy().hasHeightForWidth())
        self.spinBox_intervalx.setSizePolicy(sizePolicy)
        self.spinBox_intervalx.setKeyboardTracking(False)
        self.spinBox_intervalx.setDecimals(10)
        self.spinBox_intervalx.setMaximum(9999999.99)
        self.spinBox_intervalx.setObjectName(_fromUtf8("spinBox_intervalx"))
        self.gridLayout_3.addWidget(self.spinBox_intervalx, 1, 2, 1, 1)
        self.label_intervaly = QtGui.QLabel(self.groupBox_grid)
        self.label_intervaly.setObjectName(_fromUtf8("label_intervaly"))
        self.gridLayout_3.addWidget(self.label_intervaly, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_grid, 7, 0, 1, 2)
        self.label_composers = QtGui.QLabel(PrintDialog)
        self.label_composers.setObjectName(_fromUtf8("label_composers"))
        self.gridLayout.addWidget(self.label_composers, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PrintDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 15, 0, 1, 2)
        self.label_title = QtGui.QLabel(PrintDialog)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.gridLayout.addWidget(self.label_title, 2, 0, 1, 1)
        self.spinBox_scale = QtGui.QSpinBox(PrintDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_scale.sizePolicy().hasHeightForWidth())
        self.spinBox_scale.setSizePolicy(sizePolicy)
        self.spinBox_scale.setKeyboardTracking(False)
        self.spinBox_scale.setPrefix(_fromUtf8("1:"))
        self.spinBox_scale.setMinimum(1)
        self.spinBox_scale.setMaximum(1000000000)
        self.spinBox_scale.setSingleStep(1)
        self.spinBox_scale.setObjectName(_fromUtf8("spinBox_scale"))
        self.gridLayout.addWidget(self.spinBox_scale, 3, 1, 1, 1)
        self.comboBox_composers = QtGui.QComboBox(PrintDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_composers.sizePolicy().hasHeightForWidth())
        self.comboBox_composers.setSizePolicy(sizePolicy)
        self.comboBox_composers.setObjectName(_fromUtf8("comboBox_composers"))
        self.gridLayout.addWidget(self.comboBox_composers, 1, 1, 1, 1)
        self.checkBox_scalebar = QtGui.QCheckBox(PrintDialog)
        self.checkBox_scalebar.setObjectName(_fromUtf8("checkBox_scalebar"))
        self.gridLayout.addWidget(self.checkBox_scalebar, 9, 0, 1, 1)
        self.checkBox_legend = QtGui.QCheckBox(PrintDialog)
        self.checkBox_legend.setObjectName(_fromUtf8("checkBox_legend"))
        self.gridLayout.addWidget(self.checkBox_legend, 10, 0, 1, 1)
        self.button_mapCartouche = QtGui.QPushButton(PrintDialog)
        self.button_mapCartouche.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_mapCartouche.sizePolicy().hasHeightForWidth())
        self.button_mapCartouche.setSizePolicy(sizePolicy)
        self.button_mapCartouche.setObjectName(_fromUtf8("button_mapCartouche"))
        self.gridLayout.addWidget(self.button_mapCartouche, 8, 1, 1, 1)
        self.label_fileformat = QtGui.QLabel(PrintDialog)
        self.label_fileformat.setObjectName(_fromUtf8("label_fileformat"))
        self.gridLayout.addWidget(self.label_fileformat, 14, 0, 1, 1)
        self.lineEdit_title = QtGui.QLineEdit(PrintDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_title.sizePolicy().hasHeightForWidth())
        self.lineEdit_title.setSizePolicy(sizePolicy)
        self.lineEdit_title.setObjectName(_fromUtf8("lineEdit_title"))
        self.gridLayout.addWidget(self.lineEdit_title, 2, 1, 1, 1)
        self.checkBox_mapCartouche = QtGui.QCheckBox(PrintDialog)
        self.checkBox_mapCartouche.setObjectName(_fromUtf8("checkBox_mapCartouche"))
        self.gridLayout.addWidget(self.checkBox_mapCartouche, 8, 0, 1, 1)
        self.label_scale = QtGui.QLabel(PrintDialog)
        self.label_scale.setObjectName(_fromUtf8("label_scale"))
        self.gridLayout.addWidget(self.label_scale, 3, 0, 1, 1)
        self.comboBox_fileformat = QtGui.QComboBox(PrintDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_fileformat.sizePolicy().hasHeightForWidth())
        self.comboBox_fileformat.setSizePolicy(sizePolicy)
        self.comboBox_fileformat.setObjectName(_fromUtf8("comboBox_fileformat"))
        self.gridLayout.addWidget(self.comboBox_fileformat, 14, 1, 1, 1)
        self.previewGraphic = QtGui.QGraphicsView(PrintDialog)
        self.previewGraphic.setEnabled(False)
        self.previewGraphic.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.previewGraphic.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.previewGraphic.setInteractive(False)
        self.previewGraphic.setObjectName(_fromUtf8("previewGraphic"))
        self.gridLayout.addWidget(self.previewGraphic, 13, 0, 1, 2)
        self.label_unitWarning = QtGui.QLabel(PrintDialog)
        self.label_unitWarning.setStyleSheet(_fromUtf8("QLabel { background: orange; font-weight:bold; border-radius: 5px; padding: 5px; }"))
        self.label_unitWarning.setWordWrap(True)
        self.label_unitWarning.setObjectName(_fromUtf8("label_unitWarning"))
        self.gridLayout.addWidget(self.label_unitWarning, 0, 0, 1, 2)

        self.retranslateUi(PrintDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PrintDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PrintDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PrintDialog)
        PrintDialog.setTabOrder(self.comboBox_composers, self.lineEdit_title)
        PrintDialog.setTabOrder(self.lineEdit_title, self.spinBox_scale)
        PrintDialog.setTabOrder(self.spinBox_scale, self.lineedit_xmin)
        PrintDialog.setTabOrder(self.lineedit_xmin, self.lineedit_ymax)
        PrintDialog.setTabOrder(self.lineedit_ymax, self.checkBox_mapCartouche)
        PrintDialog.setTabOrder(self.checkBox_mapCartouche, self.button_mapCartouche)
        PrintDialog.setTabOrder(self.button_mapCartouche, self.checkBox_scalebar)
        PrintDialog.setTabOrder(self.checkBox_scalebar, self.comboBox_crs)
        PrintDialog.setTabOrder(self.comboBox_crs, self.spinBox_intervalx)
        PrintDialog.setTabOrder(self.spinBox_intervalx, self.spinBox_intervaly)
        PrintDialog.setTabOrder(self.spinBox_intervaly, self.checkBox_gridAnnotations)
        PrintDialog.setTabOrder(self.checkBox_gridAnnotations, self.comboBox_fileformat)
        PrintDialog.setTabOrder(self.comboBox_fileformat, self.previewGraphic)
        PrintDialog.setTabOrder(self.previewGraphic, self.buttonBox)

    def retranslateUi(self, PrintDialog):
        PrintDialog.setWindowTitle(_translate("PrintDialog", "Print", None))
        self.label_border.setText(_translate("PrintDialog", "Border:", None))
        self.label_extent.setText(_translate("PrintDialog", "Extent:", None))
        self.spinBox_border.setSuffix(_translate("PrintDialog", " mm", None))
        self.label_xmax.setText(_translate("PrintDialog", "X Max.:", None))
        self.label_xmin.setText(_translate("PrintDialog", "X Min.:", None))
        self.label_ymax.setText(_translate("PrintDialog", "Y Max.:", None))
        self.label_ymin.setText(_translate("PrintDialog", "Y Min.:", None))
        self.groupBox_grid.setTitle(_translate("PrintDialog", "Grid", None))
        self.label_crs.setText(_translate("PrintDialog", "Coordinate system:", None))
        self.label_intervalx.setText(_translate("PrintDialog", "Interval X:", None))
        self.checkBox_gridAnnotations.setText(_translate("PrintDialog", "Coordinate labels", None))
        self.label_intervaly.setText(_translate("PrintDialog", "Interval Y:", None))
        self.label_composers.setText(_translate("PrintDialog", "Layout:", None))
        self.label_title.setText(_translate("PrintDialog", "Title:", None))
        self.checkBox_scalebar.setText(_translate("PrintDialog", "Scalebar", None))
        self.checkBox_legend.setText(_translate("PrintDialog", "Legend", None))
        self.button_mapCartouche.setText(_translate("PrintDialog", "Edit map cartouche", None))
        self.label_fileformat.setText(_translate("PrintDialog", "File format:", None))
        self.checkBox_mapCartouche.setText(_translate("PrintDialog", "Map cartouche", None))
        self.label_scale.setText(_translate("PrintDialog", "Scale:", None))
        self.label_unitWarning.setText(_translate("PrintDialog", "Only meter based coordinate systems are supported in variable extent mode.", None))

from qgis.gui import QgsCollapsibleGroupBox
