# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kastendialog.ui'
#
# Created: Tue Sep 15 11:30:18 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_KastenDialog(object):
    def setupUi(self, KastenDialog):
        KastenDialog.setObjectName(_fromUtf8("KastenDialog"))
        KastenDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        KastenDialog.resize(400, 566)
        self.verticalLayout = QtGui.QVBoxLayout(KastenDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(KastenDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.uebungsdatumDE = QtGui.QDateEdit(KastenDialog)
        self.uebungsdatumDE.setObjectName(_fromUtf8("uebungsdatumDE"))
        self.horizontalLayout.addWidget(self.uebungsdatumDE)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(KastenDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.klassifizierungLE = QtGui.QLineEdit(KastenDialog)
        self.klassifizierungLE.setObjectName(_fromUtf8("klassifizierungLE"))
        self.horizontalLayout_2.addWidget(self.klassifizierungLE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(KastenDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.uebungsorganisationLE = QtGui.QLineEdit(KastenDialog)
        self.uebungsorganisationLE.setObjectName(_fromUtf8("uebungsorganisationLE"))
        self.horizontalLayout_3.addWidget(self.uebungsorganisationLE)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(KastenDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.kursbezeichnungLE = QtGui.QLineEdit(KastenDialog)
        self.kursbezeichnungLE.setObjectName(_fromUtf8("kursbezeichnungLE"))
        self.horizontalLayout_4.addWidget(self.kursbezeichnungLE)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(KastenDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.truppenbezeichnungLE = QtGui.QLineEdit(KastenDialog)
        self.truppenbezeichnungLE.setObjectName(_fromUtf8("truppenbezeichnungLE"))
        self.horizontalLayout_5.addWidget(self.truppenbezeichnungLE)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(KastenDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.decknameLE = QtGui.QLineEdit(KastenDialog)
        self.decknameLE.setObjectName(_fromUtf8("decknameLE"))
        self.horizontalLayout_6.addWidget(self.decknameLE)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(KastenDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.kartenumschreibungLE = QtGui.QLineEdit(KastenDialog)
        self.kartenumschreibungLE.setObjectName(_fromUtf8("kartenumschreibungLE"))
        self.horizontalLayout_7.addWidget(self.kartenumschreibungLE)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(KastenDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.beilagebezeichnungLE = QtGui.QLineEdit(KastenDialog)
        self.beilagebezeichnungLE.setObjectName(_fromUtf8("beilagebezeichnungLE"))
        self.horizontalLayout_8.addWidget(self.beilagebezeichnungLE)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(KastenDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.massstabbezeichnungLE = QtGui.QLineEdit(KastenDialog)
        self.massstabbezeichnungLE.setObjectName(_fromUtf8("massstabbezeichnungLE"))
        self.horizontalLayout_9.addWidget(self.massstabbezeichnungLE)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(KastenDialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.uebungsbezeichnungLE = QtGui.QLineEdit(KastenDialog)
        self.uebungsbezeichnungLE.setObjectName(_fromUtf8("uebungsbezeichnungLE"))
        self.horizontalLayout_10.addWidget(self.uebungsbezeichnungLE)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_12 = QtGui.QLabel(KastenDialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.dokumentbezeichnungLE = QtGui.QLineEdit(KastenDialog)
        self.dokumentbezeichnungLE.setObjectName(_fromUtf8("dokumentbezeichnungLE"))
        self.horizontalLayout_11.addWidget(self.dokumentbezeichnungLE)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(KastenDialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.ortdatumLE = QtGui.QLineEdit(KastenDialog)
        self.ortdatumLE.setObjectName(_fromUtf8("ortdatumLE"))
        self.horizontalLayout_12.addWidget(self.ortdatumLE)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.buttonBox = QtGui.QDialogButtonBox(KastenDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(KastenDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), KastenDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), KastenDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(KastenDialog)

    def retranslateUi(self, KastenDialog):
        KastenDialog.setWindowTitle(_translate("KastenDialog", "Dialog", None))
        self.label_2.setText(_translate("KastenDialog", "Übungsdatum:", None))
        self.label_3.setText(_translate("KastenDialog", "Klassifizierung:", None))
        self.label_4.setText(_translate("KastenDialog", "Übungsorganisation:", None))
        self.label_5.setText(_translate("KastenDialog", "Kursbezeichnung:", None))
        self.label_6.setText(_translate("KastenDialog", "Truppenbezeichnung:", None))
        self.label_7.setText(_translate("KastenDialog", "Deckname:", None))
        self.label_8.setText(_translate("KastenDialog", "Kartenumschreibung:", None))
        self.label_9.setText(_translate("KastenDialog", "Beilagebezeichnung:", None))
        self.label_10.setText(_translate("KastenDialog", "Massstabbezeichnung:", None))
        self.label_11.setText(_translate("KastenDialog", "Übungsbezeichnung:", None))
        self.label_12.setText(_translate("KastenDialog", "Dokumentbezeichnung:", None))
        self.label_13.setText(_translate("KastenDialog", "Ort, Datum:", None))

