# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printdialog.ui'
#
# Created: Thu Sep 17 10:35:36 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InstantPrintDialog(object):
    def setupUi(self, InstantPrintDialog):
        InstantPrintDialog.setObjectName(_fromUtf8("InstantPrintDialog"))
        InstantPrintDialog.resize(394, 670)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("printer"))
        InstantPrintDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(InstantPrintDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_composers = QtGui.QLabel(InstantPrintDialog)
        self.label_composers.setObjectName(_fromUtf8("label_composers"))
        self.horizontalLayout_2.addWidget(self.label_composers)
        self.comboBox_composers = QtGui.QComboBox(InstantPrintDialog)
        self.comboBox_composers.setObjectName(_fromUtf8("comboBox_composers"))
        self.horizontalLayout_2.addWidget(self.comboBox_composers)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(InstantPrintDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBoxScale = QtGui.QSpinBox(InstantPrintDialog)
        self.spinBoxScale.setPrefix(_fromUtf8("1:"))
        self.spinBoxScale.setMinimum(1)
        self.spinBoxScale.setMaximum(1000000000)
        self.spinBoxScale.setSingleStep(1)
        self.spinBoxScale.setObjectName(_fromUtf8("spinBoxScale"))
        self.horizontalLayout_3.addWidget(self.spinBoxScale)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_fileformat = QtGui.QLabel(InstantPrintDialog)
        self.label_fileformat.setObjectName(_fromUtf8("label_fileformat"))
        self.horizontalLayout_4.addWidget(self.label_fileformat)
        self.comboBox_fileformat = QtGui.QComboBox(InstantPrintDialog)
        self.comboBox_fileformat.setObjectName(_fromUtf8("comboBox_fileformat"))
        self.horizontalLayout_4.addWidget(self.comboBox_fileformat)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(InstantPrintDialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.titleLE = QtGui.QLineEdit(InstantPrintDialog)
        self.titleLE.setObjectName(_fromUtf8("titleLE"))
        self.horizontalLayout_7.addWidget(self.titleLE)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox_massstabbalken = QtGui.QCheckBox(InstantPrintDialog)
        self.checkBox_massstabbalken.setObjectName(_fromUtf8("checkBox_massstabbalken"))
        self.horizontalLayout.addWidget(self.checkBox_massstabbalken)
        self.checkBox_legende = QtGui.QCheckBox(InstantPrintDialog)
        self.checkBox_legende.setObjectName(_fromUtf8("checkBox_legende"))
        self.horizontalLayout.addWidget(self.checkBox_legende)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtGui.QFrame(InstantPrintDialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.comboBox_crs = QtGui.QComboBox(self.frame)
        self.comboBox_crs.setObjectName(_fromUtf8("comboBox_crs"))
        self.horizontalLayout_6.addWidget(self.comboBox_crs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spinBox_intervalx = QtGui.QDoubleSpinBox(self.frame)
        self.spinBox_intervalx.setDecimals(5)
        self.spinBox_intervalx.setMaximum(9999999.99)
        self.spinBox_intervalx.setObjectName(_fromUtf8("spinBox_intervalx"))
        self.horizontalLayout_5.addWidget(self.spinBox_intervalx)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.spinBox_intervaly = QtGui.QDoubleSpinBox(self.frame)
        self.spinBox_intervaly.setDecimals(5)
        self.spinBox_intervaly.setMaximum(9999999.99)
        self.spinBox_intervaly.setObjectName(_fromUtf8("spinBox_intervaly"))
        self.horizontalLayout_8.addWidget(self.spinBox_intervaly)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.checkBox_beschriftung = QtGui.QCheckBox(self.frame)
        self.checkBox_beschriftung.setObjectName(_fromUtf8("checkBox_beschriftung"))
        self.verticalLayout_2.addWidget(self.checkBox_beschriftung)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.frame)
        self.kastenButton = QtGui.QPushButton(InstantPrintDialog)
        self.kastenButton.setObjectName(_fromUtf8("kastenButton"))
        self.verticalLayout.addWidget(self.kastenButton)
        self.previewGraphic = QtGui.QGraphicsView(InstantPrintDialog)
        self.previewGraphic.setObjectName(_fromUtf8("previewGraphic"))
        self.verticalLayout.addWidget(self.previewGraphic)
        self.buttonBox = QtGui.QDialogButtonBox(InstantPrintDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(InstantPrintDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), InstantPrintDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), InstantPrintDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(InstantPrintDialog)

    def retranslateUi(self, InstantPrintDialog):
        InstantPrintDialog.setWindowTitle(_translate("InstantPrintDialog", "Instant Print", None))
        self.label_composers.setText(_translate("InstantPrintDialog", "Composer:", None))
        self.label.setText(_translate("InstantPrintDialog", "Scale:", None))
        self.label_fileformat.setText(_translate("InstantPrintDialog", "File format:", None))
        self.label_14.setText(_translate("InstantPrintDialog", "Titel:", None))
        self.checkBox_massstabbalken.setText(_translate("InstantPrintDialog", "Massstabbalken", None))
        self.checkBox_legende.setText(_translate("InstantPrintDialog", "Legende", None))
        self.label_15.setText(_translate("InstantPrintDialog", "Koordinatengitter:", None))
        self.label_2.setText(_translate("InstantPrintDialog", "Interval X:", None))
        self.label_3.setText(_translate("InstantPrintDialog", "Interval Y:", None))
        self.checkBox_beschriftung.setText(_translate("InstantPrintDialog", "Beschriftung", None))
        self.kastenButton.setText(_translate("InstantPrintDialog", "Kartenkartusche", None))

